-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "basePrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "flavors" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "productSizes" JSONB NOT NULL DEFAULT '[]';
